package com.hushunjian.springcloud.client.user.mapper;

import com.hushunjian.springcloud.client.user.domain.Hello;
import com.hushunjian.springcloud.client.user.domain.HelloExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface HelloMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hello
     *
     * @mbg.generated Sat May 11 19:16:48 CST 2019
     */
    long countByExample(HelloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hello
     *
     * @mbg.generated Sat May 11 19:16:48 CST 2019
     */
    int deleteByExample(HelloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hello
     *
     * @mbg.generated Sat May 11 19:16:48 CST 2019
     */
    @Delete({
        "delete from hello",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hello
     *
     * @mbg.generated Sat May 11 19:16:48 CST 2019
     */
    @Insert({
        "insert into hello (id, message)",
        "values (#{id,jdbcType=VARCHAR}, #{message,jdbcType=VARCHAR})"
    })
    int insert(Hello record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hello
     *
     * @mbg.generated Sat May 11 19:16:48 CST 2019
     */
    int insertSelective(Hello record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hello
     *
     * @mbg.generated Sat May 11 19:16:48 CST 2019
     */
    List<Hello> selectByExample(HelloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hello
     *
     * @mbg.generated Sat May 11 19:16:48 CST 2019
     */
    @Select({
        "select",
        "id, message",
        "from hello",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("com.hushunjian.springcloud.client.user.mapper.HelloMapper.BaseResultMap")
    Hello selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hello
     *
     * @mbg.generated Sat May 11 19:16:48 CST 2019
     */
    int updateByExampleSelective(@Param("record") Hello record, @Param("example") HelloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hello
     *
     * @mbg.generated Sat May 11 19:16:48 CST 2019
     */
    int updateByExample(@Param("record") Hello record, @Param("example") HelloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hello
     *
     * @mbg.generated Sat May 11 19:16:48 CST 2019
     */
    int updateByPrimaryKeySelective(Hello record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hello
     *
     * @mbg.generated Sat May 11 19:16:48 CST 2019
     */
    @Update({
        "update hello",
        "set message = #{message,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Hello record);
}