package com.hushunjian.springcloud.client.user.domain;

public class Hello {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hello.id
     *
     * @mbg.generated Sat May 11 19:16:48 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hello.message
     *
     * @mbg.generated Sat May 11 19:16:48 CST 2019
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hello.id
     *
     * @return the value of hello.id
     *
     * @mbg.generated Sat May 11 19:16:48 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hello.id
     *
     * @param id the value for hello.id
     *
     * @mbg.generated Sat May 11 19:16:48 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hello.message
     *
     * @return the value of hello.message
     *
     * @mbg.generated Sat May 11 19:16:48 CST 2019
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hello.message
     *
     * @param message the value for hello.message
     *
     * @mbg.generated Sat May 11 19:16:48 CST 2019
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }
}