package com.hushunjian.springcloud.client.user.domain;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hsj_user.id
     *
     * @mbg.generated Sat May 18 20:55:23 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hsj_user.user_name
     *
     * @mbg.generated Sat May 18 20:55:23 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hsj_user.login_name
     *
     * @mbg.generated Sat May 18 20:55:23 CST 2019
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hsj_user.passward
     *
     * @mbg.generated Sat May 18 20:55:23 CST 2019
     */
    private String passward;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hsj_user.mobile_phone
     *
     * @mbg.generated Sat May 18 20:55:23 CST 2019
     */
    private String mobilePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hsj_user.telephone_number
     *
     * @mbg.generated Sat May 18 20:55:23 CST 2019
     */
    private String telephoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hsj_user.address
     *
     * @mbg.generated Sat May 18 20:55:23 CST 2019
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hsj_user.id
     *
     * @return the value of hsj_user.id
     *
     * @mbg.generated Sat May 18 20:55:23 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hsj_user.id
     *
     * @param id the value for hsj_user.id
     *
     * @mbg.generated Sat May 18 20:55:23 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hsj_user.user_name
     *
     * @return the value of hsj_user.user_name
     *
     * @mbg.generated Sat May 18 20:55:23 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hsj_user.user_name
     *
     * @param userName the value for hsj_user.user_name
     *
     * @mbg.generated Sat May 18 20:55:23 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hsj_user.login_name
     *
     * @return the value of hsj_user.login_name
     *
     * @mbg.generated Sat May 18 20:55:23 CST 2019
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hsj_user.login_name
     *
     * @param loginName the value for hsj_user.login_name
     *
     * @mbg.generated Sat May 18 20:55:23 CST 2019
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hsj_user.passward
     *
     * @return the value of hsj_user.passward
     *
     * @mbg.generated Sat May 18 20:55:23 CST 2019
     */
    public String getPassward() {
        return passward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hsj_user.passward
     *
     * @param passward the value for hsj_user.passward
     *
     * @mbg.generated Sat May 18 20:55:23 CST 2019
     */
    public void setPassward(String passward) {
        this.passward = passward == null ? null : passward.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hsj_user.mobile_phone
     *
     * @return the value of hsj_user.mobile_phone
     *
     * @mbg.generated Sat May 18 20:55:23 CST 2019
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hsj_user.mobile_phone
     *
     * @param mobilePhone the value for hsj_user.mobile_phone
     *
     * @mbg.generated Sat May 18 20:55:23 CST 2019
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hsj_user.telephone_number
     *
     * @return the value of hsj_user.telephone_number
     *
     * @mbg.generated Sat May 18 20:55:23 CST 2019
     */
    public String getTelephoneNumber() {
        return telephoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hsj_user.telephone_number
     *
     * @param telephoneNumber the value for hsj_user.telephone_number
     *
     * @mbg.generated Sat May 18 20:55:23 CST 2019
     */
    public void setTelephoneNumber(String telephoneNumber) {
        this.telephoneNumber = telephoneNumber == null ? null : telephoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hsj_user.address
     *
     * @return the value of hsj_user.address
     *
     * @mbg.generated Sat May 18 20:55:23 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hsj_user.address
     *
     * @param address the value for hsj_user.address
     *
     * @mbg.generated Sat May 18 20:55:23 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}